Bump `bitflags` to v2
rust-mobile/android-activity pull request #85
Opened 2023-05-28 18:10 UTC by daxpedda

Changelog: https://github.com/bitflags/bitflags/blob/2.0.0/CHANGELOG.md#200.

This is a breaking change. The API that is implemented by the macro is now different.

I was a bit liberal with deriving `std` traits on public types, which mimics the behavior of `bitflags` v1, let me know if we don't need all these traits. Potentially we could at least drop `PartialOrd` and `Ord`.

[Replaces https://github.com/zakarumych/gpu-alloc/pull/70](https://github.com/rust-mobile/android-activity/pull/83).

2023-08-01 14:45 UTC, rib requested changes
Thanks, looks good except for deriving PartialOrd/Ord for the flags which I'm not sure we want.

Thanks if you update the branch with that tweak but no worries if not I can tweak before merging.

2023-08-01 14:45 UTC, rib commented on android-activity/src/lib.rs
> +    #[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
same as above, these flags don't have a natural ordering so we probably shouldn't derive `PartialOrd/Ord`

2023-08-01 14:45 UTC, rib commented on android-activity/src/input.rs
> +    #[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
I guess we shouldn't include `PartialOrd/Ord` here

2023-08-03 08:07 UTC, MarijnS95 commented on android-activity/src/input.rs
> +    #[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
It is quite a nice feat that `bitflags` now doesn't give you some of these "nonsense" default derives :)

2023-08-03 10:14 UTC, rib commented on android-activity/src/input.rs
> +    #[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
Just removed these and rebased the branch

2023-08-03 10:16 UTC, merged

2023-08-04 13:53 UTC, daxpedda commented
Apologies for my absence, thanks for getting this done!